name: Deploy sandbox branch

on:
  push:
    branches:
      - sandbox

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        region: [eu-west-1, us-east-1, us-west-2]
        #region: [eu-west-1]
    env:
      LOG_LEVEL: debug # debug | info | notice | warning | error
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: serverless deploy to ${{ matrix.region }}
        uses: serverless/github-action@master
        with:
          args: deploy --region ${{ matrix.region }}
        env:
          AWS_DEFAULT_REGION: ${{ matrix.region }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          IOT_ENDPOINT: ${{ secrets.IOT_ENDPOINT_SANDBOX }}
          SKILL_ID: ${{ secrets.SKILL_ID_SANDBOX }}
          ALEXA_CLIENT_ID: ${{ secrets.ALEXA_CLIENT_ID_SANDBOX }}
          ALEXA_CLIENT_SECRET: ${{ secrets.ALEXA_CLIENT_SECRET_SANDBOX }}
          HASH_SECRET: ${{ secrets.HASH_SECRET_SANDBOX }}
